### ISSUE TITLE
Duplicating a sap laser with a Prism can cause heavy lag spikes or even crash the game

### ISSUE THREAD

**Issue by kapzduke** [liplum/CyberIO#1]

**Comment by liplum** [comment]
Thank for your issue. I'm sorry about this mod crashed your game, and I've fixed it and other bugs in the oncoming v3 version. But  now the project has progressed too much, so that It's not easy to reversion. If it's important to you, I'll fix that instantly.

**Comment by liplum** [comment]
Thank you! The CyberIO v3 is released just now, which means it's fixed . If you had any problem on Prism, please contact with me. So I will close this issue now.

**Comment by liplum** [comment]
Now I created a new branch for development, so that I could fix bug or add some details except for a large update immediately.
