### ISSUE TITLE
[Foo's client V7] No idea what this is but i got this error on start

### ISSUE THREAD

**Issue by TheEt1234** [liplum/CyberIO#25]
Hope this doesn't have anything to do with my gpu (because it seems to be something shader related)
Mod setup:
Cyber IO (of course)
Time control (irrelevant)
UI lib (maybe important no idea)
here's the log
[crash-report-07_11_2022_13_29_45.txt](https://github.com/liplum/CyberIO/files/9083509/crash-report-07_11_2022_13_29_45.txt)

EDIT: other info is in the file

**Comment by liplum** [comment]
Yes, the TvStatic shader didn't compile on your device.
It might be because your OpenGL is in old version.
**I need more inforamtion about OpenGL version and graphic card.**

**Comment by liplum** [comment]
You should try to upgrade CyberIO to [v3.5](https://github.com/liplum/CyberIO/releases/tag/v3.5).
I might resolve it in this version, if I rememeber correctly.

**Comment by TheEt1234** [comment]
@liplum after googling how to get this info, is this helpfull

```
>glxinfo | grep "OpenGL"
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) HD Graphics 4400 (HSW GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 22.1.3
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6 (Compatibility Profile) Mesa 22.1.3
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 22.1.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

**Comment by TheEt1234** [comment]
> You should try to upgrade CyberIO to [v3.5](https://github.com/liplum/CyberIO/releases/tag/v3.5). I might resolve it in this version, if I rememeber correctly.

thanks i'll try that

**Comment by TheEt1234** [comment]
it still failed


edit: let me check again because it says 3.4

another edit: it's the same again (including the description) i double checked

**Comment by liplum** [comment]
Sorry, I haven't tested it on Foo client yet. The foo client probably enabled another context version of OpenGL.
Does it work on the official client? I mean, [anuke's client](https://github.com/Anuken/Mindustry/releases/tag/v135.2).

**Comment by TheEt1234** [comment]
is there a way to have 2 clients without the campaign and other things mixing
if not then i will wait for the next update i guess

**Comment by liplum** [comment]
> is there a way to have 2 clients without the campaign mixing

For now, no one makes a Mindustry Launcher to manage the saves.
If you don't want to bother with the saves/settings mixing or something else, just await me to test the foo client later.

I will keep this issue until I solve it.
I'm glad that you want to play Cyber IO.
Have a good day, and enjoy your game and other mods.

**Comment by liplum** [comment]
Cyber IO was updated to v4.1. Does this issue still happen?

**Comment by littlekatter330** [comment]
yes @liplum

**Comment by littlekatter330** [comment]
i got the same error as unit factory

**Comment by littlekatter330** [comment]
somehow

**Comment by liplum** [comment]
I've tested a lot with Foo's Client, and Cyber IO v5 works properly.
But, as of today, Foo's Client v7 doesn't support v141, so the latest Cyber IO v5.1 doesn't work on it.
