### ISSUE TITLE
crash when loading the game

### ISSUE THREAD

**Issue by littlekatter330** [liplum/CyberIO#37]
for some reason the game crashes with the mod. it has the same crash reason as unit factory.
[crash-report-10_06_2022_06_48_55.txt](https://github.com/liplum/CyberIO/files/9724137/crash-report-10_06_2022_06_48_55.txt)

**Comment by littlekatter330** [comment]
build 139

**Comment by liplum** [comment]
It's due to the new version v139.
I will fix it and make a new release soon, about 1 day.

**Comment by littlekatter330** [comment]
ok

**Comment by littlekatter330** [comment]
oh and this is not the first time this crash happened to me
[crash-report-10_04_2022_18_32_24.txt](https://github.com/liplum/CyberIO/files/9724177/crash-report-10_04_2022_18_32_24.txt)

**Comment by liplum** [comment]
> oh and this is not the first time this crash happened to me [crash-report-10_04_2022_18_32_24.txt](https://github.com/liplum/CyberIO/files/9724177/crash-report-10_04_2022_18_32_24.txt)

Thanks. Now it's the time to analyze it.
