### ISSUE TITLE
V7 Startup Crash (index can't be >= size: 1 >= 1)

### ISSUE THREAD

**Issue by aarrbba123** [liplum/CyberIO#38]
Crash Report:
[crash-report-10_19_2022_20_41_55.txt](https://github.com/liplum/CyberIO/files/9820547/crash-report-10_19_2022_20_41_55.txt)

**Comment by aarrbba123** [comment]
...and i just realised that the mod supports up to v136 (still relevant though)

**Comment by aarrbba123** [comment]
💀 💀 💀  #37

**Comment by liplum** [comment]
Sorry, I forgot to update the mod

**Comment by littlekatter330** [comment]
oh
